### ISSUE TITLE
Request - add trained weights.

### ISSUE THREAD

**Issue by ofirkris** [SaiHemanthBR/SkyRegion#1]
Hi, thanks for sharing this project - can you share your weights?

**Comment by bshreddy** [comment]
Sorry for the late reply 😅. I didn't train the model on the entire dataset and this is still a work in progress.

You can get trained weights by running download_models.py,.
In case that doesn't work, use this link:
https://drive.google.com/file/d/1-5BYzr7V0WfswmVTsA2qyBBDWqv09hsr/view?usp=drivesdk

Dataset: http://cs.uky.edu/~jacobs/datasets/skyfinder/
